In [21]:
import numpy as np
# matrix standardisation
def normalize(mat):
    mean = np.mean(mat,axis=0)
    std = np.std(mat,axis=0)
    mat = (mat-mean)/std
    return mat
    
    
    

In [22]:
mat = np.array([[1,2,3],[4,5,6]])

In [23]:
normalize(mat)

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

In [27]:
np.random.seed(10)
data = np.random.randn(10,5)
data

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597],
       [-0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688,  1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125],
       [ 1.67262221,  0.09914922,  1.39799638, -0.27124799,  0.61320418],
       [-0.26731719, -0.54930901,  0.1327083 , -0.47614201,  1.30847308],
       [ 0.19501328,  0.40020999, -0.33763234,  1.25647226, -0.7319695 ],
       [ 0.66023155, -0.35087189, -0.93943336, -0.48933722, -0.80459114],
       [-0.21269764, -0.33914025,  0.31216994,  0.56515267, -0.14742026]])

In [30]:
std_data = normalize(data)

In [31]:
np.mean(std_data)

-1.3322676295501878e-17

In [32]:
np.mean(data)

0.10248622016734768

In [33]:
np.std(data)

0.9009602327711386

In [34]:
np.std(std_data)

1.0

In [35]:
np.mean(data,axis=0)

array([ 0.15597887, -0.14361085, -0.14349015,  0.54785837,  0.09569486])

In [36]:
np.mean(std_data,axis=0)

array([-1.66533454e-17, -1.66533454e-17,  2.22044605e-17, -1.08940634e-16,
       -2.22044605e-17])

In [37]:
std_data

array([[ 1.19157938,  1.03667044, -1.76897443, -0.60742636,  0.67307511],
       [-0.88796659,  0.49380622,  0.31803035, -0.59358473, -0.34610856],
       [ 0.28081127,  1.62538938, -1.0366899 ,  0.52462246,  0.1702215 ],
       [ 0.29308724, -1.19852949,  0.35158037,  1.02286966, -1.50520879],
       [-2.16269558, -1.93089421,  0.51679612,  2.00615553,  1.31633308],
       [ 1.53724838,  0.29300869,  1.94509631, -0.89447865,  0.66266248],
       [-0.42904693, -0.48967315,  0.34851591, -1.11822656,  1.55294328],
       [ 0.03956473,  0.65638569, -0.24497474,  0.77381892, -1.0598111 ],
       [ 0.51110343, -0.25016176, -1.00434625, -1.13263596, -1.15280195],
       [-0.37368533, -0.2360018 ,  0.57496627,  0.01888568, -0.31130506]])

In [43]:
#find distance
p = np.random.rand(10,2)
q = np.random.rand(20,2)

numpy.ndarray

In [60]:
def distance(point,q):
    D = (np.sqrt((q[:,0]-point[0])**2 + (point[1]-q[:,1])**2))
    return D

In [69]:
%%timeit
D = []
for i in range(p.shape[0]):
    dist = distance(p[i],q)
    D.append(dist)
D = np.array(D)
D.shape

60.7 µs ± 3.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
